import {
    cilAsteriskCircle,
    cilArrowThickFromLeft,
    cilCalendarCheck,
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifPl,
    cifUs,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowBottom,
    cilArrowRight,
    cilArrowTop,
    cilBasket,
    cilBell,
    cilBellExclamation,
    cilBold,
    cilBookmark,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloudDownload,
    cilCode,
    cilCommentSquare,
    cilCreditCard,
    cilCursor,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilFile,
    cilFeaturedPlaylist,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilItalic,
    cilJustifyCenter,
    cilLayers,
    cilList,
    cilListNumbered,
    cilLibraryAdd,
    cilLocationPin,
    cilLockLocked,
    cilLoop,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMenu,
    cilMoon,
    cilNotes,
    cilNoteAdd,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPlaylistAdd,
    cilPrint,
    cilPuzzle,
    cilReportSlash,
    cilSave,
    cilSettings,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilSun,
    cilTags,
    cilTask,
    cilTrash,
    cilUnderline,
    cilUser,
    cilUserPlus,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilFolder,
    cilClipboard,
    cilContact,
    cilWeightlifitng,
    cilXCircle,
    cilPlus,
  } from '@coreui/icons';
  
  export const iconSubset = {
    cilAsteriskCircle,
    cilArrowThickFromLeft,
    cilCalendarCheck,
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifPl,
    cifUs,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowBottom,
    cilArrowRight,
    cilArrowTop,
    cilBasket,
    cilBell,
    cilBellExclamation,
    cilBold,
    cilBookmark,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloudDownload,
    cilCode,
    cilCommentSquare,
    cilCreditCard,
    cilCursor,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilFeaturedPlaylist,
    cilFile,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilItalic,
    cilJustifyCenter,
    cilLayers,
    cilList,
    cilLibraryAdd,
    cilListNumbered,
    cilLocationPin,
    cilLockLocked,
    cilLoop,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMenu,
    cilMoon,
    cilNotes,
    cilNoteAdd,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPlaylistAdd,
    cilPrint,
    cilPuzzle,
    cilReportSlash,
    cilSave,
    cilSettings,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilSun,
    cilTags,
    cilTask,
    cilTrash,
    cilUnderline,
    cilUser,
    cilUserPlus,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilFolder,
    cilClipboard,
    cilContact,
    cilWeightlifitng,
    cilXCircle,
    cilPlus
  };
  
  export enum IconSubset {
    cilAsteriskCircle = 'cilAsteriskCircle',
    cilArrowThickFromLeft = 'cilArrowThickFromLeft',
    cilCalendarCheck = 'cilCalendarCheck',
    cibCcAmex = 'cibCcAmex',
    cibCcApplePay = 'cibCcApplePay',
    cibCcMastercard = 'cibCcMastercard',
    cibCcPaypal = 'cibCcPaypal',
    cibCcStripe = 'cibCcStripe',
    cibCcVisa = 'cibCcVisa',
    cibFacebook = 'cibFacebook',
    cibGoogle = 'cibGoogle',
    cibLinkedin = 'cibLinkedin',
    cibSkype = 'cibSkype',
    cibTwitter = 'cibTwitter',
    cifBr = 'cifBr',
    cifEs = 'cifEs',
    cifFr = 'cifFr',
    cifIn = 'cifIn',
    cifPl = 'cifPl',
    cifUs = 'cifUs',
    cilAlignCenter = 'cilAlignCenter',
    cilAlignLeft = 'cilAlignLeft',
    cilAlignRight = 'cilAlignRight',
    cilApplicationsSettings = 'cilApplicationsSettings',
    cilArrowBottom = 'cilArrowBottom',
    cilArrowRight = 'cilArrowRight',
    cilArrowTop = 'cilArrowTop',
    cilBasket = 'cilBasket',
    cilBell = 'cilBell',
    cilBellExclamation = 'cilBellExclamation',
    cilBold = 'cilBold',
    cilBookmark = 'cilBookmark',
    cilCalculator = 'cilCalculator',
    cilCalendar = 'cilCalendar',
    cilChart = 'cilChart',
    cilChartPie = 'cilChartPie',
    cilCheck='cilCheck',
    cilChevronLeft = 'cilChevronLeft',
    cilChevronRight = 'cilChevronRight',
    cilCloudDownload = 'cilCloudDownload',
    cilCode = 'cilCode',
    cilCommentSquare = 'cilCommentSquare',
    cilCreditCard = 'cilCreditCard',
    cilCursor = 'cilCursor',
    cilDollar = 'cilDollar',
    cilDrop = 'cilDrop',
    cilEnvelopeClosed = 'cilEnvelopeClosed',
    cilEnvelopeOpen = 'cilEnvelopeOpen',
    cilFeaturedPlaylist = 'cilFeaturedPlaylist',
    cilFile = 'cilFile',
    cilHome = 'cilHome',
    cilInbox = 'cilInbox',
    cilIndentDecrease = 'cilIndentDecrease',
    cilIndentIncrease = 'cilIndentIncrease',
    cilItalic = 'cilItalic',
    cilJustifyCenter = 'cilJustifyCenter',
    cilLayers = 'cilLayers',
    cilList = 'cilList',
    cilListNumbered = 'cilListNumbered',
    cilLibraryAdd = 'cilLibraryAdd',
    cilLocationPin = 'cilLocationPin',
    cilLockLocked = 'cilLockLocked',
    cilLoop = 'cilLoop',
    cilMagnifyingGlass = 'cilMagnifyingGlass',
    cilMap = 'cilMap',
    cilMediaPlay = 'cilMediaPlay',
    cilMenu = 'cilMenu',
    cilMoon = 'cilMoon',
    cilNotes = 'cilNotes',
    cilNoteAdd = 'cilNoteAdd',
    cilOptions = 'cilOptions',
    cilPaperclip = 'cilPaperclip',
    cilPaperPlane = 'cilPaperPlane',
    cilPen = 'cilPen',
    cilPencil = 'cilPencil',
    cilPeople = 'cilPeople',
    cilPlaylistAdd = 'cilPlaylistAdd',
    cilPrint = 'cilPrint',
    cilPuzzle = 'cilPuzzle',
    cilReportSlash = 'cilReportSlash',
    cilSave = 'cilSave',
    cilSettings = 'cilSettings',
    cilShare = 'cilShare',
    cilShareAll = 'cilShareAll',
    cilShareBoxed = 'cilShareBoxed',
    cilSpeech = 'cilSpeech',
    cilSpeedometer = 'cilSpeedometer',
    cilSpreadsheet = 'cilSpreadsheet',
    cilStar = 'cilStar',
    cilSun = 'cilSun',
    cilTags = 'cilTags',
    cilTask = 'cilTask',
    cilTrash = 'cilTrash',
    cilUnderline = 'cilUnderline',
    cilUser = 'cilUser',
    cilUserPlus = 'cilUserPlus',
    cilUserFemale = 'cilUserFemale',
    cilUserFollow = 'cilUserFollow',
    cilUserUnfollow = 'cilUserUnfollow',
    cilFolder = 'cilFolder',
    cilClipboard = 'cilClipboard',
    cilContact = 'cilContact',
    cilWeightlifitng = 'cilWeightlifitng',
    cilXCircle = 'cilXCircle',
    cilPlus = 'cilPlus'
  }
  